import type { Prisma } from "@prisma/client";

const logoPlaceholder = (name: string) =>
  `<img draggable="true" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='70' viewBox='0 0 180 70'%3E%3Crect width='178' height='68' x='1' y='1' rx='8' fill='%23f8fafc' stroke='%2394a3b8' stroke-dasharray='5 4'/%3E%3Ctext x='90' y='40' text-anchor='middle' font-family='Arial' font-size='14' fill='%2364748b'%3ELOGO%3C/text%3E%3C/svg%3E" alt="" title="{{${name}}}" data-variable-name="${name}" data-variable-type="image" data-image-fit="contain" contenteditable="false" style="width:150px;height:60px;object-fit:contain;display:block;margin:0 0 12px auto" />`;

export const EXAMPLE_TEMPLATES = [
  {
    name: "Umowa o pracę",
    description:
      "Praktyczny polski wzór umowy o pracę z danymi stron, miejscem pracy, etatem, wynagrodzeniem i podpisami.",
    content: `${logoPlaceholder("LogoPracodawcy")}<p style="text-align:right">{{Miejscowosc}}, {{DataUmowy}}</p><h1 style="text-align:center">UMOWA O PRACĘ</h1><p>zawarta pomiędzy:</p><p><strong>{{NazwaPracodawcy}}</strong>, z siedzibą w {{AdresPracodawcy}}, NIP {{NipPracodawcy}}, reprezentowanym przez {{Reprezentant}}, zwanym dalej „Pracodawcą”,</p><p>a</p><p><strong>{{ImieNazwisko}}</strong>, zamieszkałym/ą {{AdresPracownika}}, zwanym/ą dalej „Pracownikiem”.</p><h2 style="text-align:center">§ 1. Rodzaj i miejsce pracy</h2><p>1. Pracodawca zatrudnia Pracownika na stanowisku <strong>{{Stanowisko}}</strong>.</p><p>2. Miejscem wykonywania pracy jest {{MiejscePracy}}.</p><p>3. Umowa zostaje zawarta {{RodzajUmowy}} od dnia {{DataRozpoczecia}}.</p><h2 style="text-align:center">§ 2. Wymiar czasu pracy i wynagrodzenie</h2><p>1. Pracownik będzie zatrudniony w wymiarze {{WymiarEtatu}} etatu.</p><p>2. Wynagrodzenie zasadnicze wynosi <strong>{{Wynagrodzenie}} PLN brutto miesięcznie</strong>.</p><p>3. Wynagrodzenie będzie wypłacane zgodnie z zasadami obowiązującymi u Pracodawcy.</p><h2 style="text-align:center">§ 3. Postanowienia końcowe</h2><p>W sprawach nieuregulowanych niniejszą umową zastosowanie mają właściwe przepisy prawa pracy. Umowę sporządzono w dwóch jednobrzmiących egzemplarzach, po jednym dla każdej ze stron.</p><table style="width:100%;margin-top:48px"><tbody><tr><td style="width:50%;text-align:center">_________________________<br>Pracodawca</td><td style="width:50%;text-align:center">_________________________<br>Pracownik</td></tr></tbody></table>`,
    variables: [
      {
        name: "LogoPracodawcy",
        label: "Logo pracodawcy",
        type: "image",
        imageWidth: 150,
        imageHeight: 60,
        imageAlign: "right",
        imageFit: "contain",
      },
      {
        name: "Miejscowosc",
        label: "Miejscowość",
        type: "text",
        required: true,
      },
      {
        name: "DataUmowy",
        label: "Data zawarcia umowy",
        type: "date",
        defaultValueMode: "current",
        dateFormat: "DD.MM.YYYY",
      },
      {
        name: "NazwaPracodawcy",
        label: "Nazwa pracodawcy",
        type: "text",
        required: true,
      },
      {
        name: "AdresPracodawcy",
        label: "Adres pracodawcy",
        type: "text",
        required: true,
      },
      {
        name: "NipPracodawcy",
        label: "NIP pracodawcy",
        type: "text",
        mask: "9999999999",
        required: true,
      },
      {
        name: "Reprezentant",
        label: "Osoba reprezentująca pracodawcę",
        type: "text",
        required: true,
      },
      {
        name: "ImieNazwisko",
        label: "Imię i nazwisko pracownika",
        type: "text",
        required: true,
      },
      {
        name: "AdresPracownika",
        label: "Adres pracownika",
        type: "text",
        required: true,
      },
      { name: "Stanowisko", label: "Stanowisko", type: "text", required: true },
      {
        name: "MiejscePracy",
        label: "Miejsce wykonywania pracy",
        type: "text",
        required: true,
      },
      {
        name: "RodzajUmowy",
        label: "Rodzaj umowy",
        type: "select",
        options: [
          "na czas nieokreślony",
          "na czas określony",
          "na okres próbny",
        ],
        required: true,
      },
      {
        name: "DataRozpoczecia",
        label: "Data rozpoczęcia pracy",
        type: "date",
        dateFormat: "DD.MM.YYYY",
        required: true,
      },
      {
        name: "WymiarEtatu",
        label: "Wymiar etatu",
        type: "select",
        options: ["1/1", "3/4", "1/2", "1/4"],
        required: true,
      },
      {
        name: "Wynagrodzenie",
        label: "Wynagrodzenie brutto",
        type: "number",
        decimalPlaces: 2,
        decimalSeparator: ",",
        thousandsSeparator: "space",
        required: true,
      },
    ],
  },
  {
    name: "Umowa zlecenia",
    description:
      "Wzór umowy zlecenia z zakresem czynności, okresem wykonania, wynagrodzeniem i zasadami odbioru.",
    content: `${logoPlaceholder("LogoFirmy")}<p style="text-align:right">{{Miejscowosc}}, {{DataUmowy}}</p><h1 style="text-align:center">UMOWA ZLECENIA</h1><p>zawarta pomiędzy <strong>{{Zleceniodawca}}</strong>, {{DaneZleceniodawcy}}, zwanym dalej „Zleceniodawcą”, a <strong>{{Zleceniobiorca}}</strong>, {{DaneZleceniobiorcy}}, zwanym dalej „Zleceniobiorcą”.</p><h2 style="text-align:center">§ 1. Przedmiot umowy</h2><p>Zleceniodawca powierza, a Zleceniobiorca zobowiązuje się wykonać następujące czynności:</p><p>{{ZakresZlecenia}}</p><h2 style="text-align:center">§ 2. Termin</h2><p>Zlecenie będzie wykonywane od {{DataOd}} do {{DataDo}}.</p><h2 style="text-align:center">§ 3. Wynagrodzenie</h2><p>Za prawidłowe wykonanie zlecenia Zleceniobiorcy przysługuje wynagrodzenie w wysokości <strong>{{Wynagrodzenie}} PLN brutto</strong>. Podstawą wypłaty jest potwierdzenie wykonania zlecenia.</p><h2 style="text-align:center">§ 4. Postanowienia końcowe</h2><p>Zmiany umowy wymagają formy uzgodnionej przez strony. Umowę sporządzono w dwóch jednobrzmiących egzemplarzach.</p><table style="width:100%;margin-top:48px"><tbody><tr><td style="width:50%;text-align:center">_________________________<br>Zleceniodawca</td><td style="width:50%;text-align:center">_________________________<br>Zleceniobiorca</td></tr></tbody></table>`,
    variables: [
      {
        name: "LogoFirmy",
        label: "Logo firmy",
        type: "image",
        imageWidth: 150,
        imageHeight: 60,
        imageAlign: "right",
        imageFit: "contain",
      },
      {
        name: "Miejscowosc",
        label: "Miejscowość",
        type: "text",
        required: true,
      },
      {
        name: "DataUmowy",
        label: "Data umowy",
        type: "date",
        defaultValueMode: "current",
        dateFormat: "DD.MM.YYYY",
      },
      {
        name: "Zleceniodawca",
        label: "Zleceniodawca",
        type: "text",
        required: true,
      },
      {
        name: "DaneZleceniodawcy",
        label: "Dane/adres Zleceniodawcy",
        type: "text",
        required: true,
      },
      {
        name: "Zleceniobiorca",
        label: "Zleceniobiorca",
        type: "text",
        required: true,
      },
      {
        name: "DaneZleceniobiorcy",
        label: "Dane/adres Zleceniobiorcy",
        type: "text",
        required: true,
      },
      {
        name: "ZakresZlecenia",
        label: "Zakres zlecenia",
        type: "text",
        required: true,
      },
      {
        name: "DataOd",
        label: "Data rozpoczęcia",
        type: "date",
        dateFormat: "DD.MM.YYYY",
        required: true,
      },
      {
        name: "DataDo",
        label: "Data zakończenia",
        type: "date",
        dateFormat: "DD.MM.YYYY",
        required: true,
      },
      {
        name: "Wynagrodzenie",
        label: "Wynagrodzenie brutto",
        type: "number",
        decimalPlaces: 2,
        decimalSeparator: ",",
        thousandsSeparator: "space",
        required: true,
      },
    ],
  },
  {
    name: "Protokół zdawczo-odbiorczy",
    description:
      "Praktyczny protokół odbioru usługi, prac lub przedmiotu z zakresem, wynikiem odbioru i uwagami.",
    content: `${logoPlaceholder("LogoFirmy")}<h1 style="text-align:center">PROTOKÓŁ ZDAWCZO-ODBIORCZY</h1><p style="text-align:center">sporządzony w {{Miejscowosc}} dnia {{DataOdbioru}}</p><p><strong>Przekazujący:</strong> {{Przekazujacy}}</p><p><strong>Odbierający:</strong> {{Odbierajacy}}</p><h2>1. Przedmiot odbioru</h2><p>{{PrzedmiotOdbioru}}</p><h2>2. Stan i wynik odbioru</h2><p>Strony potwierdzają, że przedmiot został przekazany i sprawdzony. Wynik odbioru: <strong>{{WynikOdbioru}}</strong>.</p><h2>3. Uwagi / zastrzeżenia</h2><p>{{Uwagi}}</p><p>Protokół sporządzono w dwóch jednobrzmiących egzemplarzach.</p><table style="width:100%;margin-top:48px"><tbody><tr><td style="width:50%;text-align:center">_________________________<br>Przekazujący</td><td style="width:50%;text-align:center">_________________________<br>Odbierający</td></tr></tbody></table>`,
    variables: [
      {
        name: "LogoFirmy",
        label: "Logo",
        type: "image",
        imageWidth: 150,
        imageHeight: 60,
        imageAlign: "right",
        imageFit: "contain",
      },
      {
        name: "Miejscowosc",
        label: "Miejscowość",
        type: "text",
        required: true,
      },
      {
        name: "DataOdbioru",
        label: "Data odbioru",
        type: "date",
        defaultValueMode: "current",
        dateFormat: "DD.MM.YYYY",
      },
      {
        name: "Przekazujacy",
        label: "Przekazujący",
        type: "text",
        required: true,
      },
      {
        name: "Odbierajacy",
        label: "Odbierający",
        type: "text",
        required: true,
      },
      {
        name: "PrzedmiotOdbioru",
        label: "Przedmiot odbioru",
        type: "text",
        required: true,
      },
      {
        name: "WynikOdbioru",
        label: "Wynik odbioru",
        type: "select",
        options: ["bez zastrzeżeń", "z zastrzeżeniami", "odmowa odbioru"],
        required: true,
      },
      { name: "Uwagi", label: "Uwagi / zastrzeżenia", type: "text" },
    ],
  },
  {
    name: "Oferta handlowa",
    description:
      "Profesjonalny układ oferty z logo, numerem, klientem, zakresem, ceną, terminem i ważnością oferty.",
    content: `${logoPlaceholder("LogoFirmy")}<p style="text-align:right"><strong>OFERTA NR {{NumerOferty}}</strong><br>{{Miejscowosc}}, {{DataOferty}}</p><h1>Oferta handlowa</h1><p>Dla: <strong>{{Klient}}</strong><br>{{AdresKlienta}}</p><p>Szanowni Państwo,</p><p>w odpowiedzi na zapytanie przedstawiamy ofertę na <strong>{{PrzedmiotOferty}}</strong>.</p><h2>Zakres oferty</h2><p>{{ZakresOferty}}</p><h2>Warunki handlowe</h2><table style="width:100%;border-collapse:collapse"><tbody><tr><td><strong>Cena netto</strong></td><td>{{CenaNetto}} PLN</td></tr><tr><td><strong>Termin realizacji</strong></td><td>{{TerminRealizacji}}</td></tr><tr><td><strong>Ważność oferty</strong></td><td>do {{WaznaDo}}</td></tr></tbody></table><p style="margin-top:28px">W razie pytań zapraszamy do kontaktu:<br><strong>{{OsobaKontaktowa}}</strong><br>{{Kontakt}}</p>`,
    variables: [
      {
        name: "LogoFirmy",
        label: "Logo firmy",
        type: "image",
        imageWidth: 150,
        imageHeight: 60,
        imageAlign: "right",
        imageFit: "contain",
      },
      {
        name: "NumerOferty",
        label: "Numer oferty",
        type: "text",
        required: true,
      },
      {
        name: "Miejscowosc",
        label: "Miejscowość",
        type: "text",
        required: true,
      },
      {
        name: "DataOferty",
        label: "Data oferty",
        type: "date",
        defaultValueMode: "current",
        dateFormat: "DD.MM.YYYY",
      },
      { name: "Klient", label: "Klient", type: "text", required: true },
      { name: "AdresKlienta", label: "Adres klienta", type: "text" },
      {
        name: "PrzedmiotOferty",
        label: "Przedmiot oferty",
        type: "text",
        required: true,
      },
      {
        name: "ZakresOferty",
        label: "Zakres oferty",
        type: "text",
        required: true,
      },
      {
        name: "CenaNetto",
        label: "Cena netto",
        type: "number",
        decimalPlaces: 2,
        decimalSeparator: ",",
        thousandsSeparator: "space",
        required: true,
      },
      { name: "TerminRealizacji", label: "Termin realizacji", type: "text" },
      {
        name: "WaznaDo",
        label: "Oferta ważna do",
        type: "date",
        dateFormat: "DD.MM.YYYY",
      },
      { name: "OsobaKontaktowa", label: "Osoba kontaktowa", type: "text" },
      { name: "Kontakt", label: "Telefon / e-mail", type: "text" },
    ],
  },
] as const;

export function exampleTemplateCreateData(
  organizationId: string,
): Prisma.TemplateCreateManyInput[] {
  return EXAMPLE_TEMPLATES.map((template) => ({
    organizationId,
    name: template.name,
    description: template.description,
    content: template.content,
    variablesJson: JSON.stringify(template.variables),
    isExample: true,
  }));
}
